"""Add timezone support

Revision ID: 2d146bb376b2
Revises: 1bc80ffc7f63
Create Date: 2025-06-11 16:39:07.799691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d146bb376b2'
down_revision: Union[str, None] = '1bc80ffc7f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('meetings', 'original_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('meetings', 'summarized_content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_meetings_title'), 'meetings', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetings_title'), table_name='meetings')
    op.alter_column('meetings', 'summarized_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meetings', 'original_content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('meetings', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
